### ISSUE TITLE
NullPointerException in initGui?

### ISSUE THREAD

**Issue by coder0107git** [coder0107git/cheerpj3-jpexs-ffdec#1]
<details><summary>Expand error</summary>

```
Jan 09, 2024 10:58:36 PM com.jpexs.decompiler.flash.gui.View execInEventDispatch
SEVERE: null
java.lang.reflect.InvocationTargetException
	at java.lang.Exception.<init>(Unknown Source)
	at java.lang.ReflectiveOperationException.<init>(Unknown Source)
	at java.lang.reflect.InvocationTargetException.<init>(Unknown Source)
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at com.jpexs.decompiler.flash.gui.View.execInEventDispatch(Unknown Source)
	at com.jpexs.decompiler.flash.gui.Main.initGui(Unknown Source)
	at com.jpexs.decompiler.flash.gui.Main.main(Unknown Source)
Caused by: java.lang.NullPointerException
	at sun.nio.fs.LinuxWatchService.inotifyInit(Unknown Source)
	at sun.nio.fs.LinuxWatchService.<init>(Unknown Source)
	at sun.nio.fs.LinuxFileSystem.newWatchService(Unknown Source)
	at com.jpexs.decompiler.flash.gui.Main.lambda$initGui$2(Unknown Source)
	at com.jpexs.decompiler.flash.gui.Main$$Lambda$14.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)


Jan 09, 2024 10:58:57 PM com.jpexs.decompiler.flash.gui.View execInEventDispatch
SEVERE: null
java.lang.reflect.InvocationTargetException
	at java.lang.Exception.<init>(Unknown Source)
	at java.lang.ReflectiveOperationException.<init>(Unknown Source)
	at java.lang.reflect.InvocationTargetException.<init>(Unknown Source)
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at com.jpexs.decompiler.flash.gui.View.execInEventDispatch(Unknown Source)
	at com.jpexs.decompiler.flash.gui.Main.main(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.jpexs.decompiler.flash.gui.DebugStackPanel.<init>(Unknown Source)
	at com.jpexs.decompiler.flash.gui.MainPanel.<init>(Unknown Source)
	at com.jpexs.decompiler.flash.gui.MainFrameRibbon.<init>(Unknown Source)
	at com.jpexs.decompiler.flash.gui.Main.ensureMainFrame(Unknown Source)
	at com.jpexs.decompiler.flash.gui.Main.showModeFrame(Unknown Source)
	at com.jpexs.decompiler.flash.gui.Main.lambda$main$3(Unknown Source)
	at com.jpexs.decompiler.flash.gui.Main$$Lambda$17.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

</details>

**Comment by coder0107git** [comment]
Fixed
