### ISSUE TITLE
Can't play sound

### ISSUE THREAD

**Issue by coder0107git** [coder0107git/cheerpj3-jpexs-ffdec#3]
Probably a CheerpJ error.

<details><summary>Log</summary>

```
Jan 13, 2024 10:48:33 PM java.util.logging.LogManager$RootLogger log
SEVERE: Uncaught exception in thread: Sound tag player
java.lang.IllegalArgumentException: No line matching interface SourceDataLine supporting format PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian is supported.
	at java.lang.Exception.<init>(Unknown Source)
	at java.lang.RuntimeException.<init>(Unknown Source)
	at java.lang.IllegalArgumentException.<init>(Unknown Source)
	at javax.sound.sampled.AudioSystem.getLine(Unknown Source)
	at com.jpexs.decompiler.flash.gui.SoundTagPlayer.openSound(Unknown Source)
	at com.jpexs.decompiler.flash.gui.SoundTagPlayer.access$000(Unknown Source)
	at com.jpexs.decompiler.flash.gui.SoundTagPlayer$2.run(Unknown Source)
```

</details>

**Comment by coder0107git** [comment]
Last call it makes is [here](https://github.com/jindrapetrik/jpexs-decompiler/blob/version20.1.0/src/com/jpexs/decompiler/flash/gui/SoundTagPlayer.java#L227).

**Comment by coder0107git** [comment]
As of right now, CheerpJ 3 doesn't support audio. CheerpJ 2 seems to but that isn't an option.

**Comment by coder0107git** [comment]
It sounds like CheerpJ 3.1 has audio support but I need to look into this again later.
