### ISSUE TITLE
`java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location`

### ISSUE THREAD

**Issue by coder0107git** [coder0107git/cheerpj3-jpexs-ffdec#4]
This seems that it might be a CheerpJ issue.

<details><summary>Error log (click to expand)</summary>

```
Jan 19, 2024 2:25:30 AM java.util.logging.LogManager$RootLogger log
SEVERE: Uncaught exception in thread: AWT-EventQueue-0
java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.lang.Exception.<init>(Unknown Source)
	at java.lang.RuntimeException.<init>(Unknown Source)
	at java.lang.IllegalStateException.<init>(Unknown Source)
	at java.awt.IllegalComponentStateException.<init>(Unknown Source)
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Unknown Source)
	at java.awt.Component.getLocationOnScreen(Unknown Source)
	at javax.swing.text.JTextComponent$InputMethodRequestsHandler.getTextLocation(Unknown Source)
	at com.leaningtech.cheerpj.CheerpJInputMethod.moveCompositionBox(Unknown Source)
	at com.leaningtech.cheerpj.CheerpJInputMethod.dispatchEvent(Unknown Source)
	at sun.awt.im.InputContext.dispatchEvent(Unknown Source)
	at sun.awt.im.InputMethodContext.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

</details>

**Comment by coder0107git** [comment]
Unable to reproduce
